events { worker_connections 1024; }

http {
    # הגדרת Cache כדי להוריד עומס מה-API וה-Redis
    proxy_cache_path /var/cache/nginx keys_zone=video_cache:10m max_size=500m inactive=60s;

    server {
        listen 80;

        location / {
            # מעביר הכל ל-API (שמוגדר בשם השירות שלו בדוקר)
            proxy_pass http://api:3000;
            
            # הגדרות Cache לצ'אנקים (.ts)
            proxy_cache video_cache;
            proxy_cache_valid 200 2s; # שומר כל צ'אנק ל-2 שניות בזיכרון
            
            add_header X-Cache-Status $upstream_cache_status; # אינדיקציה אם זה מה-Cache
            add_header Access-Control-Allow-Origin *;
        }
    }
}
