//base setup for Express server and Redis connection
import express, { Request, Response } from 'express';
import Redis from 'ioredis';
import cors from 'cors';
import path from 'path';
import fs from 'fs';

const app = express();
const redis = new Redis(process.env.REDIS_URL || 'redis://redis:6379');const PORT = 3000;

//path to HLS output directory (same as receiver's output)
const HLS_DIR = '/app/hls_out';
app.use(cors());


/**
 * HOW IT WORKS:
 * 1. The player first requests '/live.m3u8' and reads the list of segments (e.g., 'stream0.ts').
 * 2. The player automatically constructs a new URL by appending the segment name to the base URL.
 * 3. This ':segment' route acts as a wildcard to catch those automatic requests.
 * 4. We then take the segment name, fetch the binary data from Redis, and serve it to the player.
 */

app.get('/live.m3u8', (req: Request, res: Response) => {
    //serve the HLS playlist file generated by the receiver
    const filePath = path.join(HLS_DIR, 'stream.m3u8');

    //check if playlist file exists before serving
    if (fs.existsSync(filePath)) {
        res.setHeader('Content-Type', 'application/x-mpegURL');
        fs.createReadStream(filePath).pipe(res);
    } else {
        res.status(404).send('Stream playlist not found. Is the receiver running?');
    }
});

app.get('/:segment', async (req: Request, res: Response) => {
    //asking for a specific .ts segment (e.g., /segment1.ts), look it
    const { segment } = req.params;
    //construct Redis key for the requested segment
    const redisKey = `video:seg:${segment}`;

    try {
        //try to get the segment data from Redis
        const data = await redis.getBuffer(redisKey);

        if (data) {
            res.setHeader('Content-Type', 'video/MP2T');
            res.send(data);
        } else {
            console.log(`[API]: Segment ${segment} not found in Redis`);
            res.status(404).send('Segment expired or not found');
        }
    } catch (err) {
        console.error('[API Error]:', err);
        res.status(500).send('Internal Server Error');
    }
});

app.listen(PORT, () => {
    console.log(`Frontend API is running at http://localhost:${PORT}`);
    console.log(`Playlist URL: http://localhost:3000/live.m3u8`);
});